//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPConnectionData.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmsTagsTable
    {
        public int Id { get; set; }
        public string AvigilionAlarm { get; set; }
        public string AvigilionSite { get; set; }
        public Nullable<int> JacquesTagId { get; set; }
    }
}
